name: Test Action
on:
  pull_request:
    branches: ["main"]

jobs:
  chatgpt-pr-reviewer:
    runs-on: ubuntu-latest
    name: Use ChatGPT for PR review

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Review PR diff
        id: chatgpt_pr_reviewer
        uses: ./ # Uses an action in the root directory
        # or use a released Github Action
        # uses: osl-incubator/github-actions-chatgpt-pr-reviewer@1.0.3
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          openai_model: 'gpt-4-1106-preview'
          openai_temperature: 0.5
          openai_max_tokens: 2048
          openai_rules_json_array: >-
            [{
              "rule": "Code should follow the SOLID design principles",
            }, {
              "rule": "All text, including code, should be free of obvious spelling errors.",
              "good": [
                "The quick brown fox jumps over the lazy dog.",
                "card_template",
                "receive",
                "shippingLabel"
              ],
              "bad": [
                "The quack brown fox jumps over the lazy dog.",
                "card_templat",
                "recieve",
                "shipingLabel",
                "shippingLable"
              ]
            }]
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_pr_id: ${{ github.event.number }}

      - name: Print the result
        run: |
          echo "${{ steps.chatgpt_pr_reviewer.outputs.chatgpt_result }}"
